version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis-server
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_volume:/data
    networks:
      - app_network

  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  redis_volume:
  postgres_volume:

networks:
  app_network:
    external: true
